# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
# sudo: false
sudo: required
cache: packages

### From https://github.com/eddelbuettel/rcppgsl/blob/master/.travis.yml
### (Edited)

dist: trusty

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-rcpp libgsl0-dev
