
# This file is automatically generated, you probably don't want to edit this

modmedOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "modmedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            meds = NULL,
            pred = NULL,
            xmmod = NULL,
            mymod = NULL,
            covsm = NULL,
            covsy = NULL,
            estMethod = "standard",
            bootstrap = 1000,
            test = TRUE,
            ci = FALSE,
            ciWidth = 95,
            pm = FALSE,
            paths = FALSE,
            label = FALSE,
            estPlot = FALSE, ...) {

            super$initialize(
                package='semMed',
                name='modmed',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..meds <- jmvcore::OptionVariables$new(
                "meds",
                meds,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..pred <- jmvcore::OptionVariable$new(
                "pred",
                pred,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..xmmod <- jmvcore::OptionVariable$new(
                "xmmod",
                xmmod,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..mymod <- jmvcore::OptionVariable$new(
                "mymod",
                mymod,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..covsm <- jmvcore::OptionVariables$new(
                "covsm",
                covsm,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covsy <- jmvcore::OptionVariables$new(
                "covsy",
                covsy,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..estMethod <- jmvcore::OptionList$new(
                "estMethod",
                estMethod,
                options=list(
                    "standard",
                    "bootstrap"),
                default="standard")
            private$..bootstrap <- jmvcore::OptionInteger$new(
                "bootstrap",
                bootstrap,
                min=1,
                default=1000)
            private$..test <- jmvcore::OptionBool$new(
                "test",
                test,
                default=TRUE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..pm <- jmvcore::OptionBool$new(
                "pm",
                pm,
                default=FALSE)
            private$..paths <- jmvcore::OptionBool$new(
                "paths",
                paths,
                default=FALSE)
            private$..label <- jmvcore::OptionBool$new(
                "label",
                label,
                default=FALSE)
            private$..estPlot <- jmvcore::OptionBool$new(
                "estPlot",
                estPlot,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..meds)
            self$.addOption(private$..pred)
            self$.addOption(private$..xmmod)
            self$.addOption(private$..mymod)
            self$.addOption(private$..covsm)
            self$.addOption(private$..covsy)
            self$.addOption(private$..estMethod)
            self$.addOption(private$..bootstrap)
            self$.addOption(private$..test)
            self$.addOption(private$..ci)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..pm)
            self$.addOption(private$..paths)
            self$.addOption(private$..label)
            self$.addOption(private$..estPlot)
        }),
    active = list(
        dep = function() private$..dep$value,
        meds = function() private$..meds$value,
        pred = function() private$..pred$value,
        xmmod = function() private$..xmmod$value,
        mymod = function() private$..mymod$value,
        covsm = function() private$..covsm$value,
        covsy = function() private$..covsy$value,
        estMethod = function() private$..estMethod$value,
        bootstrap = function() private$..bootstrap$value,
        test = function() private$..test$value,
        ci = function() private$..ci$value,
        ciWidth = function() private$..ciWidth$value,
        pm = function() private$..pm$value,
        paths = function() private$..paths$value,
        label = function() private$..label$value,
        estPlot = function() private$..estPlot$value),
    private = list(
        ..dep = NA,
        ..meds = NA,
        ..pred = NA,
        ..xmmod = NA,
        ..mymod = NA,
        ..covsm = NA,
        ..covsy = NA,
        ..estMethod = NA,
        ..bootstrap = NA,
        ..test = NA,
        ..ci = NA,
        ..ciWidth = NA,
        ..pm = NA,
        ..paths = NA,
        ..label = NA,
        ..estPlot = NA)
)

modmedResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Moderated mediation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Moderated mediation"))}))

modmedBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "modmedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'semMed',
                name = 'modmed',
                version = c(1,0,0),
                options = options,
                results = modmedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Moderated mediation
#'
#' 
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable
#' @param meds a string naming the mediator variable
#' @param pred a string naming the predictor variable
#' @param xmmod a string naming the predictor variable
#' @param mymod a string naming the predictor variable
#' @param covsm a vector with strings naming the covariates
#' @param covsy a vector with strings naming the covariates
#' @param estMethod \code{'standard'} (default), or \code{'bootstrap'}, the
#'   estimation method to use
#' @param bootstrap a number between 1 and 100000 (default: 1000) specifying
#'   the number of  samples that need to been drawn in the bootstrap method
#' @param test \code{TRUE} (default) or \code{FALSE}, provide 'Z' and 'p'
#'   values for the mediation estimates
#' @param ci \code{TRUE} or \code{FALSE} (default), provide a confidence
#'   interval for the mediation estimates
#' @param ciWidth a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width that is used as \code{'ci'}
#' @param pm \code{TRUE} or \code{FALSE} (default), provide the percent
#'   mediation  effect size for the mediation estimates
#' @param paths \code{TRUE} or \code{FALSE} (default), provide the individual
#'   estimates of the  paths in the mediation model
#' @param label \code{TRUE} (default) or \code{FALSE}, provide insightful
#'   labels for all estimates
#' @param estPlot \code{TRUE} or \code{FALSE} (default), provide an estimate
#'   plot where for each estimator the estimated coefficient and confidence
#'   intervals are plotted.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
modmed <- function(
    data,
    dep,
    meds,
    pred,
    xmmod,
    mymod,
    covsm,
    covsy,
    estMethod = "standard",
    bootstrap = 1000,
    test = TRUE,
    ci = FALSE,
    ciWidth = 95,
    pm = FALSE,
    paths = FALSE,
    label = FALSE,
    estPlot = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('modmed requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(meds), meds, NULL),
            `if`( ! missing(pred), pred, NULL),
            `if`( ! missing(xmmod), xmmod, NULL),
            `if`( ! missing(mymod), mymod, NULL),
            `if`( ! missing(covsm), covsm, NULL),
            `if`( ! missing(covsy), covsy, NULL))

    options <- modmedOptions$new(
        dep = dep,
        meds = meds,
        pred = pred,
        xmmod = xmmod,
        mymod = mymod,
        covsm = covsm,
        covsy = covsy,
        estMethod = estMethod,
        bootstrap = bootstrap,
        test = test,
        ci = ci,
        ciWidth = ciWidth,
        pm = pm,
        paths = paths,
        label = label,
        estPlot = estPlot)

    results <- modmedResults$new(
        options = options)

    analysis <- modmedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
